spring.application.name=ChatApplication

spring.datasource.url=jdbc:mysql://localhost:3306/chat_app

spring.datasource.username=root

spring.datasource.password=loki123

spring.jpa.hibernate.ddl-auto=update

frontend.url=http://10.48.46.99:5173



server.address=10.48.46.99